from enum import Enum, unique


@unique
class ConcurrencyWorkflowTasks(Enum):
    """Specification of available tasks in this workflow as Enumerates types.
    
    NOTE: Auto-generated by Workflow2TaskEnum on 2022-01-05T17:43:30.820254Z    
    Do not edit this class manually
    """
    
    SLEEP_TIME_SOURCE = "SleepTimeSource"
    SLEEPER = "Sleeper"
