import time

# Tasks
from testspython.task_a import TaskA

# Types
from crossflow.testspython import type_a

# Streams
from crossflow.testspython.queue_a import QueueA

# Utility
from crossflow.testspython.python_tests_workflow_tasks import PythonTestsWorkflowTasks
from crossflow.runtime import BuiltinStream, Mode, LogLevel, Workflow, WorkflowConfig
from crossflow.serialization import Serializer, JsonSerializer


class PythonTestsWorkflow(Workflow):
    """NOTE: Auto-generated by Workflow2Class on 2022-01-05T17:43:34.772882Z    
    Do not edit this class manually
    """

    def __init__(
        self,
        name="",
        instance=None,
        broker_host="localhost",
        stomp_port=61613,
        mode=Mode.WORKER,
        cache=None,
        cache_enabled=True,
        delete_cache=None,
        excluded_tasks=None,
        enable_prefetch=False,
        use_ssl=False,
        ssl_key=None,
        ssl_cert=None,
        ssl_ca_certs=None,
    ):
                 
        super().__init__(name=name,
                         instance=instance,
                         broker_host=broker_host,
                         stomp_port=stomp_port,
                         mode=mode,
                         cache=cache,
                         cache_enabled=cache_enabled,
                         delete_cache=delete_cache,
                         excluded_tasks=excluded_tasks,
                         enable_prefetch=enable_prefetch,
                         use_ssl=use_ssl,
                         ssl_key=ssl_key,
                         ssl_cert=ssl_cert,
                         ssl_ca_certs=ssl_ca_certs)
                         
        # Streams
        self.queueA: QueueA = None

        # Tasks
        self.taskA = None
        if PythonTestsWorkflowTasks.TASK_A not in self._excluded_tasks:
            self.taskA = TaskA()
            self.taskA.workflow = self
            self._tasks.append(self.taskA)
        
    @classmethod
    def from_config(cls, config: WorkflowConfig):
        workflow = cls(
    		name=config.name,
            instance=config.instance,
            broker_host=config.broker_host,
            stomp_port=config.broker_port,
            mode=config.mode,
            use_ssl=config.use_ssl,
            ssl_key=config.ssl_key,
            ssl_cert=config.ssl_cert,
            ssl_ca_certs=config.ssl_ca_certs,
        )
        workflow.output_directory = config.output_directory
        return workflow

    def excluded_tasks(self, tasks=[]):
        assert isinstance(tasks, list)
        assert not tasks or [t for t in tasks if isinstance(t, PythonTestsWorkflowTasks)]
        self._excluded_tasks = tasks

    def createWorker(self):
        worker = PythonTestsWorkflow(Mode.WORKER)
        worker.instance(self._instance)
        return worker


    """
     * Run with initial delay in ms before starting execution (after creating broker
     * if master)
     * 
     * @param delay
    """
    def run(self, delay=0):
        """Run with an initial delay before starting execution

        :param delay: delay in ms before this worker will start running. Defaults to 0
        :type delay: int
        """
        self._delay=delay

        try:
            time.sleep(delay)
            self.connect()
            
            # Initialise Streams
            self.queueA = QueueA(self, self._enable_prefetch)
            self._active_streams.append(self.queueA)
            
            if (self.is_worker()):
                if not PythonTestsWorkflowTasks.TASK_A in self._excluded_tasks:
                        self.queueA.add_consumer(self.taskA, "TaskA")
        except Exception as ex:
            self.local_logger.exception("")
            self.report_internal_exception(ex)

    def getQueueA(self) -> QueueA:
        return self.queueA
        
    def getTaskA(self):
        return self.taskA
        
    def _create_serializer(self) -> Serializer:
        return JsonSerializer()

    def _register_custom_serialization_types(self):
        self._serializer.register_type(type_a.TypeA)


if __name__ == '__main__':
    config = WorkflowConfig()
    app = PythonTestsWorkflow.from_config(config)
    app.run()
    app.logger.log(LogLevel.INFO, "Finished Startup")
    while (not app.terminated):
        time.sleep(0.1)
    print("terminated")
    
