from enum import Enum, unique


@unique
class PythonTestsWorkflowTasks(Enum):
    """Specification of available tasks in this workflow as Enumerates types.
    
    NOTE: Auto-generated by Workflow2TaskEnum on 2022-01-05T17:43:34.772882Z    
    Do not edit this class manually
    """
    
    TASK_A = "TaskA"
