from typing import Union


from crossflow.runtime import Job


class TypeA(Job):
    """NOTE: Auto-generated by Type2Class on 2022-01-05T17:43:34.772882Z
    Do not edit this class manually
    """

    def __init__(self,
        foo: str = None,
        correlation_id: Union["TypeA", Job, str] = None
    ):
        super().__init__(correlation_id=correlation_id)
        self._foo = foo        

    @property
    def foo(self) -> str:
        return self._foo

    @foo.setter
    def foo(self, foo: str):
        self._foo = foo

    def __str__(self):
        return f"TypeA ( foo={str(self.foo)}, job_id={str(self.job_id)}, correlation_id={str(self.correlation_id)}, destination={str(self.destination)} )"
