from typing import Union


from crossflow.runtime import Job


class Calculation(Job):
    """NOTE: Auto-generated by Type2Class on 2022-01-05T17:43:29.450708Z
    Do not edit this class manually
    """

    def __init__(self,
        a: int = None,
        b: int = None,
        operator: str = None,
        correlation_id: Union["Calculation", Job, str] = None
    ):
        super().__init__(correlation_id=correlation_id)
        self._a = a        
        self._b = b        
        self._operator = operator        

    @property
    def a(self) -> int:
        return self._a

    @a.setter
    def a(self, a: int):
        self._a = a

    @property
    def b(self) -> int:
        return self._b

    @b.setter
    def b(self, b: int):
        self._b = b

    @property
    def operator(self) -> str:
        return self._operator

    @operator.setter
    def operator(self, operator: str):
        self._operator = operator

    def __str__(self):
        return f"Calculation ( a={str(self.a)}, b={str(self.b)}, operator={str(self.operator)}, job_id={str(self.job_id)}, correlation_id={str(self.correlation_id)}, destination={str(self.destination)} )"
