import time

# Tasks

# Types
from crossflow.calculator import calculation
from crossflow.calculator import calculation_result

# Streams
from crossflow.calculator.calculations import Calculations
from crossflow.calculator.calculation_results import CalculationResults

# Utility
from crossflow.calculator.calculator_workflow_tasks import CalculatorWorkflowTasks
from crossflow.runtime import BuiltinStream, Mode, LogLevel, Workflow, WorkflowConfig
from crossflow.serialization import Serializer, JsonSerializer


class CalculatorWorkflow(Workflow):
    """NOTE: Auto-generated by Workflow2Class on 2022-01-05T17:43:29.450708Z    
    Do not edit this class manually
    """

    def __init__(
        self,
        name="",
        instance=None,
        broker_host="localhost",
        stomp_port=61613,
        mode=Mode.WORKER,
        cache=None,
        cache_enabled=True,
        delete_cache=None,
        excluded_tasks=None,
        enable_prefetch=False,
        use_ssl=False,
        ssl_key=None,
        ssl_cert=None,
        ssl_ca_certs=None,
    ):
                 
        super().__init__(name=name,
                         instance=instance,
                         broker_host=broker_host,
                         stomp_port=stomp_port,
                         mode=mode,
                         cache=cache,
                         cache_enabled=cache_enabled,
                         delete_cache=delete_cache,
                         excluded_tasks=excluded_tasks,
                         enable_prefetch=enable_prefetch,
                         use_ssl=use_ssl,
                         ssl_key=ssl_key,
                         ssl_cert=ssl_cert,
                         ssl_ca_certs=ssl_ca_certs)
                         
        # Streams
        self.calculations: Calculations = None
        self.calculationResults: CalculationResults = None

        # Tasks
        
    @classmethod
    def from_config(cls, config: WorkflowConfig):
        workflow = cls(
    		name=config.name,
            instance=config.instance,
            broker_host=config.broker_host,
            stomp_port=config.broker_port,
            mode=config.mode,
            use_ssl=config.use_ssl,
            ssl_key=config.ssl_key,
            ssl_cert=config.ssl_cert,
            ssl_ca_certs=config.ssl_ca_certs,
        )
        workflow.output_directory = config.output_directory
        return workflow

    def excluded_tasks(self, tasks=[]):
        assert isinstance(tasks, list)
        assert not tasks or [t for t in tasks if isinstance(t, CalculatorWorkflowTasks)]
        self._excluded_tasks = tasks

    def createWorker(self):
        worker = CalculatorWorkflow(Mode.WORKER)
        worker.instance(self._instance)
        return worker


    """
     * Run with initial delay in ms before starting execution (after creating broker
     * if master)
     * 
     * @param delay
    """
    def run(self, delay=0):
        """Run with an initial delay before starting execution

        :param delay: delay in ms before this worker will start running. Defaults to 0
        :type delay: int
        """
        self._delay=delay

        try:
            time.sleep(delay)
            self.connect()
            
            # Initialise Streams
            self.calculations = Calculations(self, self._enable_prefetch)
            self._active_streams.append(self.calculations)
            
            self.calculationResults = CalculationResults(self, self._enable_prefetch)
            self._active_streams.append(self.calculationResults)
            
        except Exception as ex:
            self.local_logger.exception("")
            self.report_internal_exception(ex)

    def getCalculations(self) -> Calculations:
        return self.calculations
        
    def getCalculationResults(self) -> CalculationResults:
        return self.calculationResults
        
    def getCalculationSource(self):
        return self.calculationSource
        
    def getCalculator(self):
        return self.calculator
        
    def getCalculationResultsSink(self):
        return self.calculationResultsSink
        
    def _create_serializer(self) -> Serializer:
        return JsonSerializer()

    def _register_custom_serialization_types(self):
        self._serializer.register_type(calculation.Calculation)
        self._serializer.register_type(calculation_result.CalculationResult)
        self._serializer.register_type(calculation_result.WorkerLang)


if __name__ == '__main__':
    config = WorkflowConfig()
    app = CalculatorWorkflow.from_config(config)
    app.run()
    app.logger.log(LogLevel.INFO, "Finished Startup")
    while (not app.terminated):
        time.sleep(0.1)
    print("terminated")
    
