from enum import Enum, unique


@unique
class CalculatorWorkflowTasks(Enum):
    """Specification of available tasks in this workflow as Enumerates types.
    
    NOTE: Auto-generated by Workflow2TaskEnum on 2022-01-05T17:43:29.450708Z    
    Do not edit this class manually
    """
    
    CALCULATION_SOURCE = "CalculationSource"
    CALCULATOR = "Calculator"
    CALCULATION_RESULTS_SINK = "CalculationResultsSink"
